# Generated by Django to align the model default with the initial schema intent.
import decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="opportunity_score",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                max_digits=5,
            ),
        ),
    ]
